services:
  worker:
    build:
      context: ./app
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./app:/code/app
      - ./dlt_data:/var/dlt
    env_file:
      - worker.env
    networks:
      - etl_network
  db:
    image: postgres:alpine
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - ./minio_data:/data
    env_file:
      - minio.env
    command: server /data --console-address ":9001"
    networks:
      - etl_network

networks:
  etl_network:
    driver: bridge
