services:
  worker:
    build:
      context: ./app
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./app:/code/app
      - ./dlt_data:/var/dlt
    env_file:
      - worker.env
    networks:
      - etl_network
      - shared_network
    restart: always
  db:
    image: postgres:alpine
    env_file:
      - db.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  dremio:
    image: dremio/dremio-oss:20.1.0
    ports:
      - "9047:9047" # Web UI
      - "31010:31010" # Client connection
      - "32010:32010"
      - "45678:45678" # Inter-node communication
    volumes:
      - dremio_data:/opt/dremio/data
    environment:
      - DREMIO_MAX_MEMORY_SIZE_MB=4096
    networks:
      - etl_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - ./minio_data:/data
    env_file:
      - minio.env
    command: server /data --console-address ":9001"
    networks:
      - etl_network
    restart: always

networks:
  etl_network:
    driver: bridge
  shared_network:
    external: true

volumes:
  dremio_data:
  minio_data:
  postgres_data:
