from decouple import config

S3_ENDPOINT_URL = config("S3_ENDPOINT_URL")
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
BUCKET = config("BUCKET")
